import {beforeAll,afterAll,beforeEach,test,expect,vi} from 'vitest';
const m=vi.hoisted(()=>({scrape:vi.fn(),sendAccess:vi.fn(),analyze:vi.fn(),search:vi.fn(),email:vi.fn(),owner:{email:'owner@example.test'}}));
vi.mock('../../src/lib/scrape',async importOriginal=>({...await importOriginal<typeof import('../../src/lib/scrape')>(),scrape:m.scrape}));
vi.mock('../../src/lib/email',()=>({sendAccess:m.sendAccess,email:m.email,dashboardLink:()=> 'https://watchtower.test/dashboard'}));
vi.mock('../../src/lib/ai',()=>({analyze:m.analyze}));vi.mock('../../src/lib/search',()=>({alternatives:m.search}));
vi.mock('next/headers',()=>({cookies:()=>({get:()=>({value:tokenFor(m.owner.email)})})}));
import {tokenFor} from '../../src/lib/auth';import {db} from '../../src/lib/db';
import {POST} from '../../src/app/api/products/route';import {GET as read,PATCH} from '../../src/app/api/products/[id]/route';import {GET as cron} from '../../src/app/api/cron/check-prices/route';
const origin='https://watchtower.test';
const request=(body:unknown)=>new Request(origin+'/api/products',{method:'POST',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const input={url:'https://retailer.example/camera',email:'owner@example.test',country:'France',targetPrice:95};
async function create(){const response=await POST(request(input));expect(response.status).toBe(201);return db.product.findFirstOrThrow({where:{email:input.email}});}
beforeAll(async()=>{await db.$connect();});
afterAll(async()=>{await db.$disconnect();});
beforeEach(async()=>{await db.product.deleteMany();await db.rateLimit.deleteMany();await db.jobLock.deleteMany();m.owner.email=input.email;m.scrape.mockReset().mockResolvedValue({name:'Camera',price:100,currency:'EUR',stock:'in_stock',imageUrl:null});m.sendAccess.mockReset().mockResolvedValue(undefined);m.analyze.mockReset().mockResolvedValue({verdict:'great deal',reasoning:'Price dropped',historicalLow:90,confidence:'low',worthNotifying:true});m.search.mockReset().mockResolvedValue([{retailer:'Other',price:80,url:'https://other.example/camera',shipsToUser:'unverified'}]);m.email.mockReset().mockResolvedValue(undefined);});
test('create route persists product + initial price, then owner reads real history',async()=>{const p=await create();const r=await read(new Request(origin),{params:{id:p.id}});expect(r.status).toBe(200);const body=await r.json();expect(body.history).toHaveLength(1);expect(Number(body.history[0].price)).toBe(100);expect(body.targetPrice).toBe('95');expect(m.sendAccess).toHaveBeenCalledWith(input.email);});
test('actual cron records a second observation, analysis, alternatives and a single combined email',async()=>{const p=await create();m.scrape.mockResolvedValue({name:'Camera',price:90,currency:'EUR',stock:'in_stock',imageUrl:null});const req=new Request(origin+'/api/cron/check-prices?force=true',{headers:{authorization:'Bearer test-only-cron-secret'}});const response=await cron(req);expect(await response.json()).toMatchObject({checked:1,results:[{id:p.id,notified:true}]});const r=await read(new Request(origin),{params:{id:p.id}});const body=await r.json();expect(body.history.map((h:{price:string})=>Number(h.price))).toEqual([100,90]);expect(body.analyses[0].alternatives).toHaveLength(1);expect(body.analyses[0].notifiedAt).not.toBeNull();expect(m.email).toHaveBeenCalledOnce();expect(await db.jobLock.count()).toBe(0);});
test('duplicate product is rejected without another scrape or history entry',async()=>{await create();expect((await POST(request(input))).status).toBe(409);expect(await db.priceHistory.count()).toBe(1);expect(m.scrape).toHaveBeenCalledOnce();});
test('scrape failure persists neither product nor history',async()=>{m.scrape.mockRejectedValue(new Error('Could not find a reliable price'));expect((await POST(request(input))).status).toBe(422);expect(await db.product.count()).toBe(0);expect(await db.priceHistory.count()).toBe(0);});
test('email failure preserves the tracked product',async()=>{m.sendAccess.mockRejectedValue(new Error('mail down'));const r=await POST(request(input));expect(r.status).toBe(201);expect((await r.json()).emailSent).toBe(false);expect(await db.priceHistory.count()).toBe(1);});
test('other owners cannot read or mutate this product',async()=>{const p=await create();m.owner.email='other@example.test';expect((await read(new Request(origin),{params:{id:p.id}})).status).toBe(404);const req=new Request(origin,{method:'PATCH',headers:{origin,'Content-Type':'application/json'},body:JSON.stringify({bought:true})});expect((await PATCH(req,{params:{id:p.id}})).status).toBe(404);});
test('cron skips bought/fresh products and rejects missing authentication',async()=>{await create();expect((await cron(new Request(origin+'/api/cron/check-prices'))).status).toBe(401);const response=await cron(new Request(origin+'/api/cron/check-prices',{headers:{authorization:'Bearer test-only-cron-secret'}}));expect((await response.json()).checked).toBe(0);});
test('cron records per-product scrape errors and releases its lock',async()=>{const p=await create();m.scrape.mockRejectedValue(new Error('Retailer returned HTTP 429'));const r=await cron(new Request(origin+'/api/cron/check-prices?force=true',{headers:{authorization:'Bearer test-only-cron-secret'}}));expect((await r.json()).results[0].error).toContain('429');expect((await db.product.findUniqueOrThrow({where:{id:p.id}})).lastError).toContain('429');expect(await db.jobLock.count()).toBe(0);});

import {POST as subscribe} from '../../src/app/api/newsletter/route';
import {POST as confirmSubscription} from '../../src/app/api/newsletter/confirm/route';
import {PATCH as savePassword,POST as passwordLogin} from '../../src/app/api/password/route';
import {createHash} from 'node:crypto';
test('newsletter signup, confirmation and unsubscribe use the real schema',async()=>{await db.newsletterSubscriber.deleteMany();const r=await subscribe(request({email:'newsletter@example.test'}));expect(r.status).toBe(200);const row=await db.newsletterSubscriber.findUniqueOrThrow({where:{email:'newsletter@example.test'}});expect(row.confirmedAt).toBeNull();const text=m.email.mock.calls[0][2] as string;const token=text.match(/token=([a-f0-9]{64})/)![1];expect(createHash('sha256').update(token).digest('hex')).toBe(row.tokenHash);expect((await confirmSubscription(request({token,unsubscribe:false}))).status).toBe(200);expect((await db.newsletterSubscriber.findUniqueOrThrow({where:{id:row.id}})).confirmedAt).not.toBeNull();expect((await confirmSubscription(request({token,unsubscribe:true}))).status).toBe(200);expect(await db.newsletterSubscriber.count()).toBe(0);});
test('verified account can set a password and sign in against the real database',async()=>{await db.user.upsert({where:{email:input.email},create:{email:input.email},update:{passwordHash:null}});expect((await savePassword(request({password:'integration-test-passphrase'}))).status).toBe(200);const row=await db.user.findUniqueOrThrow({where:{email:input.email}});expect(row.passwordHash).toMatch(/^scrypt:/);expect((await passwordLogin(request({email:input.email,password:'wrong'}))).status).toBe(401);const r=await passwordLogin(request({email:input.email,password:'integration-test-passphrase'}));expect(r.status).toBe(200);expect(r.headers.get('set-cookie')).toContain('HttpOnly');});

import {DELETE as removeProduct} from '../../src/app/api/products/[id]/route';
import {POST as reactToDeal} from '../../src/app/api/deals/[id]/vote/route';
import {POST as publishFind} from '../../src/app/api/products/[id]/share/route';
import {dealFeed} from '../../src/lib/deal-feed';
async function shared(){const p=await create();await db.priceHistory.create({data:{productId:p.id,price:80,stock:'in_stock',checkedAt:new Date(Date.now()+1000)}});expect((await publishFind(request({note:'A useful discount',published:true}),{params:{id:p.id}})).status).toBe(200);return {p,f:await db.sharedFind.findUniqueOrThrow({where:{productId:p.id}})};}
test('publishing captures a truthful first-observed discount and republishing preserves reactions',async()=>{const {p,f}=await shared();expect(Number(f.referencePrice)).toBe(100);expect(Number(f.discountPercent)).toBe(20);expect((await reactToDeal(request({value:1}),{params:{id:f.id}})).status).toBe(200);await publishFind(request({note:'Updated note',published:true}),{params:{id:p.id}});expect(await db.dealVote.count({where:{findId:f.id}})).toBe(1);});
test('reactions are idempotent, switchable and removable with one vote per account',async()=>{const {f}=await shared();const vote=(value:number)=>reactToDeal(request({value}),{params:{id:f.id}});expect(await (await vote(1)).json()).toMatchObject({likes:1,dislikes:0,myVote:1});expect(await (await vote(1)).json()).toMatchObject({likes:1});expect(await (await vote(-1)).json()).toMatchObject({likes:0,dislikes:1,myVote:-1});expect(await db.dealVote.count()).toBe(1);expect(await (await vote(0)).json()).toMatchObject({likes:0,dislikes:0,myVote:0});expect(await db.dealVote.count()).toBe(0);});
test('voting rejects anonymous, cross-origin, invalid and unpublished requests',async()=>{const {f}=await shared();const params={params:{id:f.id}};m.owner.email='';expect((await reactToDeal(request({value:1}),params)).status).toBe(401);m.owner.email=input.email;expect((await reactToDeal(new Request(origin,{method:'POST'}),params)).status).toBe(403);expect((await reactToDeal(request({value:2}),params)).status).toBe(400);await db.sharedFind.update({where:{id:f.id},data:{published:false}});expect((await reactToDeal(request({value:1}),params)).status).toBe(404);expect(await db.dealVote.count()).toBe(0);});
test('only the owner can delete a product, cascading its history, analysis, shared find and votes',async()=>{const {p,f}=await shared();await reactToDeal(request({value:1}),{params:{id:f.id}});const analysis=await db.dealAnalysis.create({data:{productId:p.id,verdict:'great deal',reasoning:'Test',historicalLow:80,confidence:'low',worthNotifying:true}});await db.alternativeDeal.create({data:{productId:p.id,dealAnalysisId:analysis.id,retailer:'Other',price:70,url:'https://other.example/item',shipsToUser:'unverified'}});m.owner.email='other@example.test';expect((await removeProduct(request({}),{params:{id:p.id}})).status).toBe(404);expect(await db.product.count()).toBe(1);m.owner.email='';expect((await removeProduct(request({}),{params:{id:p.id}})).status).toBe(401);m.owner.email=input.email;expect((await removeProduct(new Request(origin,{method:'DELETE'}),{params:{id:p.id}})).status).toBe(403);expect((await removeProduct(request({}),{params:{id:p.id}})).status).toBe(200);for(const count of await Promise.all([db.product.count(),db.priceHistory.count(),db.dealAnalysis.count(),db.alternativeDeal.count(),db.sharedFind.count(),db.dealVote.count()]))expect(count).toBe(0);});
test('feed ranks all published deals before the 60 item limit and keeps unknown discounts last',async()=>{const user=await db.user.upsert({where:{email:input.email},create:{email:input.email},update:{}});const ids=Array.from({length:62},(_,i)=>'rank-'+i);await db.product.createMany({data:ids.map(id=>({id,url:'https://retailer.example/'+id,name:id,email:input.email,country:'France',currency:'EUR'}))});await db.sharedFind.createMany({data:ids.map((id,i)=>({id,productId:id,userId:user.id,name:id,url:'https://retailer.example/'+id,price:80,currency:'EUR',note:'',createdAt:new Date(1700000000000+i*1000),referencePrice:i===0?100:null,discountPercent:i===0?20:null}))});await db.dealVote.create({data:{findId:ids[0],userId:user.id,value:1}});expect((await dealFeed('recent'))[0].id).toBe('rank-61');const liked=await dealFeed('liked',user.id);expect(liked).toHaveLength(60);expect(liked[0]).toMatchObject({id:'rank-0',likes:1,myVote:1});expect((await dealFeed('discount'))[0].id).toBe('rank-0');await db.sharedFind.update({where:{id:'rank-0'},data:{published:false}});expect((await dealFeed('liked')).some(f=>f.id==='rank-0')).toBe(false);});
