import {Newsletter} from '@/components/newsletter';
import {faqs} from '@/lib/site-content';
import {outbound} from '@/lib/outbound';
import Link from 'next/link';
import {ArrowUpRight,Radar} from 'lucide-react';
import {db} from '@/lib/db';
import {ProductImage} from '@/components/product-image';
import {money} from '@/lib/format';
export const dynamic='force-dynamic';
export default async function Home(){
 const finds=await db.sharedFind.findMany({where:{published:true},orderBy:{createdAt:'desc'},take:60,select:{id:true,name:true,url:true,imageUrl:true,price:true,currency:true,note:true,createdAt:true,updatedAt:true,user:{select:{displayName:true}}}});
 return <main className="dashboard"><section className="community-hero"><span className="eyebrow"><Radar size={16}/> THE COMMUNITY LOOKOUT</span><h1>A good find.<br/><em>Worth passing on.</em></h1><p>Discover what thoughtful shoppers are finding. Track your own wishlist, then share the deals worth a second look.</p><div className="community-actions"><Link className="primary" href="/track">Track & share a find <ArrowUpRight size={17}/></Link><Link className="secondary" href="/login">Join the lookout</Link></div></section><div className="section-heading"><h2>Fresh from the community</h2><span>Shared by shoppers, open to everyone</span></div>{!finds.length?<section className="empty"><Radar size={40}/><h2>The first good find could be yours.</h2><p>Track a product and choose “Publish to the homepage” to get the community started.</p><Link className="secondary" href="/track">Share your first find →</Link></section>:<div className="product-grid">{finds.map(f=><article key={f.id} className="product-card"><div className="feed-image"><ProductImage src={f.imageUrl} name={f.name}/></div><small>{new URL(f.url).hostname}</small><h3>{f.name}</h3><div className="price-row"><strong>{money(Number(f.price),f.currency)}</strong><span>when shared</span></div>{f.note&&<p className="find-note">{f.note}</p>}<p className="subtle">Found by {f.user.displayName} · Updated <time dateTime={f.updatedAt.toISOString()}>{f.updatedAt.toLocaleDateString('en-GB',{timeZone:'UTC'})}</time></p><a className="secondary" href={outbound(f.url)} target="_blank" rel="noopener noreferrer nofollow">Check at retailer <ArrowUpRight size={15}/></a></article>)}</div>}<p className="subtle">Community finds are shopper recommendations, not verified discounts. Prices and stock can change; confirm the exact product, shipping and total at checkout.</p><section className="home-faq"><div><span className="eyebrow">BEFORE YOU DIVE IN</span><h2>A little clarity<br/><em>goes a long way.</em></h2><Link className="text-link" href="/help">All your questions, answered →</Link></div><div className="faq-list">{faqs.slice(0,4).map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section><Newsletter/></main>;
}
