'use client';
import {useLanguage} from '@/components/language-provider';
import {useId} from 'react';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,ReferenceLine,CartesianGrid} from 'recharts';
import {money} from '@/lib/format';
export function PriceChart({points,currency,compact=false,target}:{points:{price:number;date:string}[];currency:string;compact?:boolean;target?:number|null}){
 const {t,locale}=useLanguage();
 const id=useId().replace(/:/g,'');const low=points.length?Math.min(...points.map(p=>p.price)):null;const latest=points.at(-1)?.price;
 return <div className="price-chart"><div className="chart" style={{height:compact?72:260}} role="img" aria-label={points.length?t('Price history: ')+points.length+t(' observations. Latest ')+money(latest!,currency,locale)+t(', observed low ')+money(low!,currency,locale)+'.':t('No price observations yet')}><ResponsiveContainer width="100%" height="100%"><AreaChart data={points} margin={{top:15,right:compact?0:16,left:0,bottom:0}}><defs><linearGradient id={id} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-line)" stopOpacity={.16}/><stop offset="100%" stopColor="var(--chart-line)" stopOpacity={0}/></linearGradient></defs>{!compact&&<><CartesianGrid vertical={false} stroke="var(--line)" strokeDasharray="3 5"/><XAxis dataKey="date" tickFormatter={s=>new Date(s).toLocaleDateString(locale,{month:'short',day:'numeric',timeZone:'UTC'})} axisLine={false} tickLine={false} minTickGap={32} tick={{fill:'var(--muted)',fontSize:12}}/><YAxis domain={['auto','auto']} axisLine={false} tickLine={false} width={56} tick={{fill:'var(--muted)',fontSize:12}}/><Tooltip contentStyle={{background:'var(--surface)',border:'1px solid var(--line)',borderRadius:6,color:'var(--ink)',fontSize:14}} labelStyle={{color:'var(--muted)'}} itemStyle={{color:'var(--ink)'}} labelFormatter={s=>new Date(s).toLocaleString(locale,{timeZone:'UTC'})+' UTC'} formatter={(v:number)=>[money(v,currency,locale),t('Observed price')]}/>{target!=null&&<ReferenceLine y={target} stroke="var(--chart-target)" strokeDasharray="5 5"/>}</>}<Area type="linear" dataKey="price" stroke="var(--chart-line)" strokeWidth={2} fill={'url(#'+id+')'} dot={points.length===1?{r:4}:false} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>{!compact&&<details className="chart-data"><summary>{t("View recorded prices as a table")}</summary><div className="table-scroll"><table><caption className="sr-only">{t("Recorded prices and times, in")} {t(currency)}</caption><thead><tr><th scope="col">{t("Observation (UTC)")}</th><th scope="col">{t("Price")}</th></tr></thead><tbody>{points.map((p,i)=><tr key={p.date+i}><td><time dateTime={p.date}>{new Date(p.date).toLocaleString(locale,{timeZone:'UTC'})}</time></td><td>{money(p.price,currency,locale)}</td></tr>)}</tbody></table></div></details>}</div>;
}
