'use client';
import {FormEvent,useState} from 'react';
import {Link2,LoaderCircle,Check,AlertCircle} from 'lucide-react';

export function TrackForm(){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[ok,setOk]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage('');try{const res=await fetch('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:f.get('url'),email:f.get('email'),country:f.get('country'),targetPrice:f.get('target')?Number(f.get('target')):null})});const data=await res.json();setOk(res.ok);setMessage(data.message||data.error);}catch{setOk(false);setMessage('Could not reach Watchtower. Check your connection and try again.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="track-form" aria-busy={busy}><div className="form-title"><span className="observation-dot" aria-hidden="true"/><h2>Start a watch</h2></div><p>We’ll take a first look at the listing.</p><label htmlFor="url">Product URL</label><div className="input-icon"><Link2 size={18} aria-hidden="true"/><input id="url" name="url" type="url" placeholder="https://retailer.com/product" required maxLength={2000} aria-describedby="url-help" autoComplete="url"/></div><small id="url-help">Use a direct HTTPS link to the exact product.</small><div className="form-grid"><div><label htmlFor="target">Target price <span>(optional)</span></label><input id="target" name="target" type="number" min="0.01" max="999999999" step="0.01" inputMode="decimal" placeholder="e.g. 120.00" aria-describedby="target-help"/><small id="target-help">In the listing’s currency</small></div><div><label htmlFor="country">Shopping from</label><select id="country" name="country" defaultValue="Nigeria" autoComplete="country-name" aria-describedby="country-help">{['Nigeria','France','United States','United Kingdom','Germany','Canada','India','Australia','South Africa'].map(country=><option key={country}>{country}</option>)}</select><small id="country-help">For alternative retailer searches</small></div></div><label htmlFor="email">Email address</label><input id="email" name="email" type="email" placeholder="you@example.com" required maxLength={254} autoComplete="email" aria-describedby="email-help"/><small id="email-help">For your private access link and price alerts.</small><button className="primary" disabled={busy}>{busy?<><LoaderCircle className="spin" size={18} aria-hidden="true"/>Checking the listing…</>:'Track this product'}</button><p className="form-note">Up to 10 products per watchlist. Checks are best effort.</p>{message&&<p role={ok?'status':'alert'} className={ok?'notice':'error'}>{ok?<Check size={18} aria-hidden="true"/>:<AlertCircle size={18} aria-hidden="true"/>}<span>{message}</span></p>}</form>;
}
export function AccessForm(){
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[ok,setOk]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const email=new FormData(e.currentTarget).get('email');setBusy(true);setMessage('');try{const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json();setOk(r.ok);setMessage(d.message||d.error);}catch{setOk(false);setMessage('Could not send your link. Check your connection and try again.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="access-form" aria-busy={busy}><label htmlFor="access-email">Email address</label><input id="access-email" type="email" name="email" required maxLength={254} placeholder="you@example.com" autoComplete="email" aria-describedby="access-help"/><small id="access-help">Use the email associated with your watchlist.</small><button className="primary" disabled={busy}>{busy?<><LoaderCircle size={18} className="spin" aria-hidden="true"/>Sending your link…</>:'Send sign-in link'}</button>{message&&<p role={ok?'status':'alert'} className={ok?'notice':'error'}>{message}</p>}</form>;
}
