'use client';
import {useLanguage} from '@/components/language-provider';
import {useState} from 'react';
import {LoaderCircle,Check} from 'lucide-react';
export function Newsletter(){
 const {t}=useLanguage();
 const [busy,setBusy]=useState(false),[success,setSuccess]=useState(false),[error,setError]=useState('');
 return <section className="newsletter"><div><h2>{t("Keep a little")}<br/>{t("perspective in your inbox")}</h2><p>{t("Occasional Watchtower news and selected finds. Subscribe only after confirming by email.")}</p></div>{success?<div className="newsletter-success" role="status"><Check size={28} aria-hidden="true"/><h3>{t("Check your email")}</h3><p>{t("If you’re not already subscribed, your confirmation link is on its way.")}</p></div>:<form aria-busy={busy} onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const data=new FormData(e.currentTarget);const r=await fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email')})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not subscribe. Please try again.');setSuccess(true);}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}}><label htmlFor="newsletter-email">{t("Email address")}</label><div className="newsletter-input"><input id="newsletter-email" name="email" type="email" required maxLength={254} autoComplete="email" placeholder="you@example.com" aria-describedby="newsletter-help"/><button className="primary" disabled={busy}>{busy?<><LoaderCircle className="spin" size={18} aria-hidden="true"/>{t("Sending…")}</>:t('Subscribe')}</button></div><small id="newsletter-help">{t("No fixed schedule. Unsubscribe with your email link.")}</small>{error&&<p role="alert" className="error">{t(error)}</p>}</form>}</section>;
}
