'use client';
import {useLanguage} from '@/components/language-provider';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {ConfirmButton} from './confirm-button';
import {StateLabel} from './ui';
export function ShareForm({id,published,note}:{id:string;published:boolean;note:string}){
 const {t}=useLanguage();
 const [text,setText]=useState(note),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[ok,setOk]=useState(false);const router=useRouter();
 async function save(publish:boolean){setBusy(true);setMessage('');try{const r=await fetch('/api/products/'+id+'/share',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:text,published:publish})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save your find.');setOk(true);setMessage(publish?'Snapshot published. It’s now visible on the community feed.':'Find unpublished. Your watchlist and history are still saved.');router.refresh();}catch(e){setOk(false);setMessage(e instanceof Error?e.message:'Could not share this find.');}finally{setBusy(false);}}
 return <section className="share-section"><div className="share-explanation"><h2>{t("Pass on a good find")}</h2><StateLabel tone={published?'success':'neutral'}>{published?t('Published snapshot'):t('Not published')}</StateLabel><p>{t("Share the product, its latest recorded price, your note and display name. Your email, target and price history stay private.")}</p><p className="subtle">{t("Publishing saves a snapshot. Update it here when you want to share a newer price.")}</p></div><div className="share-editor"><label htmlFor="share-note">{t("Your note")} <span>{t("(optional)")}</span></label><textarea id="share-note" maxLength={500} rows={4} value={text} onChange={e=>setText(e.target.value)} placeholder={t("What should another shopper know about this find?")} aria-describedby="share-help"/><small id="share-help">{t(text.length)}{t("/500 characters · Visible to everyone when published")}</small><div className="community-actions"><button className="primary" disabled={busy} onClick={()=>save(true)}>{busy?t('Saving…'):published?t('Update public snapshot'):t('Publish this find')}</button>{published&&<ConfirmButton disabled={busy} title={t("Unpublish this find?")} description={t("Remove the snapshot from the community feed. Your private tracking and history stay saved.")} confirmLabel={t("Unpublish find")} onConfirm={()=>save(false)}>{t("Unpublish")}</ConfirmButton>}</div>{message&&<p role={ok?'status':'alert'} className={ok?'notice':'error'}>{t(message)}</p>}</div></section>;
}
