'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import {Radar,Menu,X,Sun,Moon,Search,ArrowUp,MessageCircle} from 'lucide-react';
import {outbound} from '@/lib/outbound';
export function Header({signedIn}:{signedIn:boolean}){
 const [open,setOpen]=useState(false),[dark,setDark]=useState(false);const path=usePathname();const menu=useRef<HTMLButtonElement>(null);
 useEffect(()=>{setDark(document.documentElement.dataset.theme==='dark');},[]);
 useEffect(()=>setOpen(false),[path]);
 useEffect(()=>{function escape(e:KeyboardEvent){if(e.key==='Escape'&&open){setOpen(false);menu.current?.focus();}}document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);},[open]);
 function toggle(){const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';try{localStorage.setItem('watchtower-theme',next?'dark':'light');}catch{}}
 return <header className="site-header"><div className="nav"><Link href="/" className="brand" aria-label="Watchtower home"><span className="brand-icon"><Radar size={23}/></span>watchtower<span className="beta">THE LOOKOUT</span></Link><div className="header-tools"><Link className="icon-button" href={path==='/search'?'/':'/search'} aria-label={path==='/search'?'Close search':'Search Watchtower'}>{path==='/search'?<X size={20}/>:<Search size={20}/>}</Link><button className="icon-button" onClick={toggle} aria-label={dark?'Switch to light mode':'Switch to dark mode'} aria-pressed={dark}>{dark?<Sun size={20}/>:<Moon size={20}/>}</button><button ref={menu} className="icon-button menu-toggle" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="main-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div><nav id="main-navigation" aria-label="Main navigation" className={open?'is-open':''}>{[['/','Community'],['/track','Track a product'],[signedIn?'/account':'/login',signedIn?'Account':'Sign in'],['/dashboard','My watchlist']].map(([href,label])=><Link key={href} href={href} aria-current={path===href?'page':undefined} className={href==='/dashboard'?'nav-dashboard':''}>{label}</Link>)}</nav></div></header>;
}
export function SiteTools(){const [progress,setProgress]=useState(0),[showTop,setShowTop]=useState(false),[cookies,setCookies]=useState(false);const path=usePathname();
 useEffect(()=>{try{setCookies(!localStorage.getItem('watchtower-cookie-notice'));}catch{setCookies(true);}},[]);
 useEffect(()=>{const update=()=>{const height=document.documentElement.scrollHeight-innerHeight;setProgress(height>0?Math.min(100,scrollY/height*100):0);setShowTop(scrollY>400);};update();addEventListener('scroll',update,{passive:true});addEventListener('resize',update);const observer=new ResizeObserver(update);observer.observe(document.body);return()=>{removeEventListener('scroll',update);removeEventListener('resize',update);observer.disconnect();};},[path]);
 return <><div className="scroll-progress" aria-hidden="true" style={{transform:'scaleX('+progress/100+')'}}/><div className="floating-tools">{showTop&&<button className="icon-button" aria-label="Back to top" onClick={()=>{window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});document.getElementById('content')?.focus({preventScroll:true});}}><ArrowUp size={20}/></button>}<Link className="contact-button" href="/contact" aria-label="Get in touch"><MessageCircle size={19}/><span>Get in touch</span></Link></div>{cookies&&<aside className="cookie-banner" aria-label="Cookie information"><div><strong>A small note on cookies.</strong><p>We use a sign-in cookie and store your theme preference on this device. No advertising or analytics cookies.</p><Link href="/privacy" className="text-link">Privacy & storage details</Link></div><button className="secondary" onClick={()=>{try{localStorage.setItem('watchtower-cookie-notice','seen');}catch{}setCookies(false);}}>Got it</button></aside>}</>;
}
export function Footer(){return <footer><Link className="brand" href="/"><Radar size={20}/>watchtower</Link><span>A little patience. A better price.</span><nav aria-label="Footer"><Link href="/help">Help & FAQ</Link><Link href="/privacy">Privacy</Link><Link href="/contact">Contact</Link><a href={outbound('https://github.com/wauul/watchtower')} target="_blank" rel="noopener noreferrer">Source ↗</a></nav></footer>;}
