import {DeleteProduct} from '@/components/delete-product';
import {ProductImage} from '@/components/product-image';
import Link from 'next/link';
import {Plus} from 'lucide-react';
import {sessionEmail} from '@/lib/auth';
import {db} from '@/lib/db';
import {AccessForm} from '@/components/forms';
import {PriceChart} from '@/components/chart';
import {money} from '@/lib/format';
import {PageHeading,EmptyState,StateLabel} from '@/components/ui';
export const dynamic='force-dynamic';
export const metadata={title:'My watchlist'};
export default async function Dashboard({searchParams}:{searchParams:{expired?:string}}){
 const email=sessionEmail();
 if(!email)return <main className="access"><div className="access-intro"><h1>Your private watchlist</h1><p>Sign in with an email link to see your products, price history and alerts.</p></div>{searchParams.expired&&<p className="error" role="alert">This sign-in link has expired or is invalid. Request a new link below.</p>}<AccessForm/><p className="subtle">Already set a password? <Link className="text-link" href="/login">Sign in with password</Link></p></main>;
 const products=await db.product.findMany({where:{email},include:{history:{orderBy:{checkedAt:'asc'}},analyses:{orderBy:{createdAt:'desc'},take:1}},orderBy:{createdAt:'desc'}});
 const savings:Record<string,number>={};products.forEach(p=>{if(p.boughtAt&&p.history.length&&p.boughtPrice)savings[p.currency]=(savings[p.currency]||0)+Math.max(0,Number(p.history[0].price)-Number(p.boughtPrice));});
 return <main className="dashboard"><PageHeading title="Your watchlist" description="The latest observations, all in one place. Only you can see this list." action={<Link href="/track" className="primary"><Plus size={18} aria-hidden="true"/>Track a product</Link>}/><dl className="stats"><div><dt>Actively watching</dt><dd>{products.filter(p=>!p.boughtAt).length}<span>products</span></dd></div><div><dt>Recorded savings</dt><dd>{Object.entries(savings).map(([c,v])=>money(v,c)).join(' · ')||'—'}</dd></div><div><dt>Marked as bought</dt><dd>{products.filter(p=>p.boughtAt).length}<span>products</span></dd></div></dl><div className="section-heading"><h2>Tracked products <span className="result-count">{products.length}</span></h2><p>Open a product for history, comparisons and sharing.</p></div>{!products.length?<EmptyState title="Start with something you have in mind" action={<Link href="/track" className="primary">Track your first product</Link>}>Add a retailer link and an optional target price. We’ll record observations and email you when a meaningful change is worth a look.</EmptyState>:<div className="product-grid watchlist-grid">{products.map(p=>{const price=Number(p.history.at(-1)?.price||0);const a=p.analyses[0];const state=p.boughtAt?'Bought · checks paused':p.lastError?'Check needs attention':a?.verdict||'Building history';return <article key={p.id} className="product-card watchlist-card"><Link href={'/product/'+p.id} className="watchlist-card-link"><div className="product-card-top"><div className="product-thumbnail"><ProductImage src={p.imageUrl} name={p.name}/></div><StateLabel tone={p.lastError?'warning':a?.verdict==='great deal'?'success':'neutral'}>{state}</StateLabel></div><small className="retailer-name">{new URL(p.url).hostname.replace('www.','')}</small><h3>{p.name}</h3><div className="price-row"><strong>{money(price,p.currency)}</strong><span>{p.stock.replaceAll('_',' ')}</span></div><PriceChart compact currency={p.currency} points={p.history.map(h=>({price:Number(h.price),date:h.checkedAt.toISOString()}))}/><div className="card-footer"><span>{p.targetPrice?'Target '+money(Number(p.targetPrice),p.currency):'No target set'}</span><span>{p.history.length} observations</span></div></Link><div className="watchlist-actions"><Link className="text-link" href={'/product/'+p.id}>View observations</Link><DeleteProduct id={p.id} name={p.name}/></div></article>;})}</div>}<p className="section-note">Savings compare the first tracked price with the price recorded when you marked a product as bought. Each currency is kept separate.</p></main>;
}
