import Link from 'next/link';
import { Radar,Plus,ArrowUpRight,ShoppingBag,Wallet,Activity } from 'lucide-react';
import { sessionEmail } from '@/lib/auth';
import { db } from '@/lib/db';
import { AccessForm } from '@/components/forms';
import { PriceChart } from '@/components/chart';
import { money } from '@/lib/format';
export const dynamic='force-dynamic';
export default async function Dashboard(){const email=sessionEmail();if(!email)return <main className="access"><div className="brand-icon"><Radar size={28}/></div><span className="eyebrow">YOUR PERSONAL LOOKOUT</span><h1>Your watchlist awaits.</h1><p>Enter your email for a private link.<br/>No password to remember.</p><AccessForm/></main>;
const products=await db.product.findMany({where:{email},include:{history:{orderBy:{checkedAt:'asc'}},analyses:{orderBy:{createdAt:'desc'},take:1}},orderBy:{createdAt:'desc'}});const savings:Record<string,number>={};products.forEach(p=>{if(p.boughtAt&&p.history.length&&p.boughtPrice)savings[p.currency]=(savings[p.currency]||0)+Math.max(0,Number(p.history[0].price)-Number(p.boughtPrice));});
return <main className="dashboard"><div className="page-heading"><div><span className="eyebrow">YOUR PERSONAL LOOKOUT</span><h1>The watchlist.</h1><p>Good buys take a little patience. We’ll keep an eye out.</p></div><Link href="/" className="primary"><Plus size={18}/> Track a product</Link></div><div className="stats"><div><Radar/><span>On our radar</span><strong>{products.filter(p=>!p.boughtAt).length}</strong></div><div><Wallet/><span>Savings since tracking</span><strong>{Object.entries(savings).map(([c,v])=>money(v,c)).join(' · ')||'—'}</strong></div><div><ShoppingBag/><span>Thoughtful purchases</span><strong>{products.filter(p=>p.boughtAt).length}</strong></div></div><div className="section-heading"><h2>Your products <span>{products.length}</span></h2><span><Activity size={15}/> Watching for the right moment</span></div>{!products.length?<div className="empty"><Radar size={42}/><h2>Nothing on the radar. Yet.</h2><p>Add the product you’ve been thinking about.</p><Link href="/" className="secondary">Start your first watch <ArrowUpRight size={17}/></Link></div>:<div className="product-grid">{products.map(p=>{const price=Number(p.history.at(-1)?.price||0);const a=p.analyses[0];return <Link href={`/product/${p.id}`} key={p.id} className="product-card"><div className="product-card-top"><div className="product-thumbnail">{p.imageUrl?<img src={p.imageUrl} alt="" loading="lazy" referrerPolicy="no-referrer"/>:<ShoppingBag size={34}/>}</div><span className={`badge ${a?.verdict==='great deal'?'good':''}`}>{p.boughtAt?'Bought':p.lastError?'Check needs attention':a?.verdict||'Building history'}</span></div><small>{new URL(p.url).hostname.replace('www.','')}</small><h3>{p.name}</h3><div className="price-row"><strong>{money(price,p.currency)}</strong><span>{p.stock.replaceAll('_',' ')}</span></div><PriceChart compact currency={p.currency} points={p.history.map(h=>({price:Number(h.price),date:h.checkedAt.toISOString()}))}/><div className="card-footer"><span>{p.targetPrice?`Target ${money(Number(p.targetPrice),p.currency)}`:'No target set'}</span><ArrowUpRight size={18}/></div></Link>;})}</div>}<p className="subtle">Savings compare your recorded purchase price with the first observed price. Currencies are kept separate.</p></main>;}
