import {getLanguage,getTranslator} from '@/lib/i18n/server';
import {localeFor} from '@/lib/i18n';
import {DeleteProduct} from '@/components/delete-product';
import {ProductImage} from '@/components/product-image';
import Link from 'next/link';
import {Plus} from 'lucide-react';
import {sessionEmail} from '@/lib/auth';
import {db} from '@/lib/db';
import {AccessForm} from '@/components/forms';
import {PriceChart} from '@/components/chart';
import {money} from '@/lib/format';
import {PageHeading,EmptyState,StateLabel} from '@/components/ui';
export const dynamic='force-dynamic';
export function generateMetadata(){const t=getTranslator();return {title:t('My watchlist')};}
export default async function Dashboard({searchParams}:{searchParams:{expired?:string}}){
 const t=getTranslator(),locale=localeFor(getLanguage());
 const email=sessionEmail();
 if(!email)return <main className="access"><div className="access-intro"><h1>{t("Your private watchlist")}</h1><p>{t("Sign in with an email link to see your products, price history and alerts.")}</p></div>{searchParams.expired&&<p className="error" role="alert">{t("This sign-in link has expired or is invalid. Request a new link below.")}</p>}<AccessForm/><p className="subtle">{t("Already set a password?")} <Link className="text-link" href="/login">{t("Sign in with password")}</Link></p></main>;
 const products=await db.product.findMany({where:{email},include:{history:{orderBy:{checkedAt:'asc'}},analyses:{orderBy:{createdAt:'desc'},take:1}},orderBy:{createdAt:'desc'}});
 const savings:Record<string,number>={};products.forEach(p=>{if(p.boughtAt&&p.history.length&&p.boughtPrice)savings[p.currency]=(savings[p.currency]||0)+Math.max(0,Number(p.history[0].price)-Number(p.boughtPrice));});
 return <main className="dashboard"><PageHeading title={t("Your watchlist")} description={t("The latest observations, all in one place. Only you can see this list.")} action={<Link href="/track" className="primary"><Plus size={18} aria-hidden="true"/>{t("Track a product")}</Link>}/><dl className="stats"><div><dt>{t("Actively watching")}</dt><dd>{t(products.filter(p=>!p.boughtAt).length)}<span>{t("products")}</span></dd></div><div><dt>{t("Recorded savings")}</dt><dd>{Object.entries(savings).map(([c,v])=>money(v,c,locale)).join(' · ')||'—'}</dd></div><div><dt>{t("Marked as bought")}</dt><dd>{t(products.filter(p=>p.boughtAt).length)}<span>{t("products")}</span></dd></div></dl><div className="section-heading"><h2>{t("Tracked products")} <span className="result-count">{t(products.length)}</span></h2><p>{t("Open a product for history, comparisons and sharing.")}</p></div>{!products.length?<EmptyState title={t("Start with something you have in mind")} action={<Link href="/track" className="primary">{t("Track your first product")}</Link>}>{t("Add a retailer link and an optional target price. We’ll record observations and email you when a meaningful change is worth a look.")}</EmptyState>:<div className="product-grid watchlist-grid">{products.map(p=>{const price=Number(p.history.at(-1)?.price||0);const a=p.analyses[0];const state=p.boughtAt?t('Bought · checks paused'):p.lastError?t('Check needs attention'):a?.verdict||t('Building history');return <article key={p.id} className="product-card watchlist-card"><Link href={'/product/'+p.id} className="watchlist-card-link"><div className="product-card-top"><div className="product-thumbnail"><ProductImage src={p.imageUrl} name={p.name}/></div><StateLabel tone={p.lastError?'warning':a?.verdict==='great deal'?'success':'neutral'}>{t(state)}</StateLabel></div><small className="retailer-name">{new URL(p.url).hostname.replace('www.','')}</small><h3>{p.name}</h3><div className="price-row"><strong>{money(price,p.currency,locale)}</strong><span>{t(p.stock.replaceAll('_',' '))}</span></div><PriceChart compact currency={p.currency} points={p.history.map(h=>({price:Number(h.price),date:h.checkedAt.toISOString()}))}/><div className="card-footer"><span>{p.targetPrice?t('Target ')+money(Number(p.targetPrice),p.currency,locale):t('No target set')}</span><span>{p.history.length} {t("observations")}</span></div></Link><div className="watchlist-actions"><Link className="text-link" href={'/product/'+p.id}>{t("View observations")}</Link><DeleteProduct id={p.id} name={p.name}/></div></article>;})}</div>}<p className="section-note">{t("Savings compare the first tracked price with the price recorded when you marked a product as bought. Each currency is kept separate.")}</p></main>;
}
