import Link from 'next/link';
import {db} from '@/lib/db';
import {sessionEmail} from '@/lib/auth';
import {pages,faqs} from '@/lib/site-content';
import {outbound} from '@/lib/outbound';
import {money} from '@/lib/format';
import {Search} from 'lucide-react';
import {FaqList,ExternalCue} from '@/components/ui';
export const dynamic='force-dynamic';export const metadata={title:'Search'};
export default async function SearchPage({searchParams}:{searchParams:{q?:string}}){
 const q=(typeof searchParams.q==='string'?searchParams.q:'').trim().slice(0,100),email=sessionEmail();
 const matches=q?pages.filter(p=>(p.title+' '+p.description).toLowerCase().includes(q.toLowerCase())):[],answers=q?faqs.filter(f=>f.join(' ').toLowerCase().includes(q.toLowerCase())):[];
 const [finds,products]=q?await Promise.all([db.sharedFind.findMany({where:{published:true,OR:[{name:{contains:q,mode:'insensitive'}},{note:{contains:q,mode:'insensitive'}}]},select:{id:true,name:true,url:true,price:true,currency:true,updatedAt:true},take:30,orderBy:{updatedAt:'desc'}}),email?db.product.findMany({where:{email,name:{contains:q,mode:'insensitive'}},select:{id:true,name:true},take:30}):Promise.resolve([])]):[[],[]];
 const count=matches.length+answers.length+finds.length+products.length;
 return <main className="dashboard prose-page"><h1>Find your way<br/>around the lookout</h1><form action="/search" className="site-search" role="search"><label htmlFor="site-query">Search finds, help and your watchlist</label><div className="newsletter-input"><input id="site-query" type="search" name="q" defaultValue={q} maxLength={100} placeholder="A product name or question" required aria-describedby="search-help"/><button className="primary"><Search size={18} aria-hidden="true"/>Search</button></div><small id="search-help">{email?'Your private products are included only for you.':'Sign in to include your private watchlist.'}</small></form>{q?<><p role="status" className="subtle">{count?count+' results shown for “'+q+'”':'No matches for “'+q+'”. Try a product name or a broader term.'} Up to 30 matches per product section.</p>{matches.length>0&&<section className="search-section"><h2>Site pages</h2>{matches.map(p=><Link className="search-result" href={p.url} key={p.url}><strong>{p.title}</strong><p>{p.description}</p></Link>)}</section>}{products.length>0&&<section className="search-section"><h2>Your private watchlist</h2>{products.map(p=><Link className="search-result" href={'/product/'+p.id} key={p.id}>{p.name}</Link>)}</section>}{finds.length>0&&<section className="search-section"><h2>Public finds</h2>{finds.map(f=><a className="search-result" href={outbound(f.url)} target="_blank" rel="noopener noreferrer" key={f.id}><strong>{f.name} <ExternalCue/></strong><p>{money(Number(f.price),f.currency)} when shared · Updated <time dateTime={f.updatedAt.toISOString()}>{f.updatedAt.toLocaleDateString('en-GB',{timeZone:'UTC'})}</time></p></a>)}</section>}{answers.length>0&&<section className="search-section"><h2>Help answers</h2><FaqList items={answers}/></section>}</>:<p className="subtle">Look up a public find, get a help answer, or find a page. Your private results are visible only after you sign in.</p>}</main>;
}
