import {beforeEach,expect,test,vi} from 'vitest';
import {OAuth2Client,LoginTicket} from 'google-auth-library';
import {NextRequest} from 'next/server';
const m=vi.hoisted(()=>({find:vi.fn(),upsert:vi.fn(),update:vi.fn(),session:''}));
vi.mock('@/lib/db',()=>({db:{$transaction:async(fn:any)=>fn({user:{findUnique:m.find,upsert:m.upsert,updateMany:m.update}})}}));
vi.mock('next/headers',()=>({cookies:()=>({get:()=>m.session?{value:m.session}:undefined})}));
import {accountForGoogle,beginGoogleSignIn,exchangeGoogleCode,googleCookie,googleOrigin,readGoogleTransaction} from '@/lib/google-auth';
import {tokenFor,verifyToken} from '@/lib/auth';
import {GET as start} from '@/app/api/auth/google/route';
import {GET as callback} from '@/app/api/auth/google/callback/route';
import {createHash} from 'node:crypto';
const profile={sub:'google-123',email:'member@gmail.com',email_verified:true as const,name:'Google member'};
beforeEach(()=>{vi.stubEnv('GOOGLE_CLIENT_ID','test-client.apps.googleusercontent.com');vi.stubEnv('GOOGLE_CLIENT_SECRET','test-google-secret');m.session='';m.find.mockResolvedValue(null);m.upsert.mockResolvedValue({id:'user-1',email:profile.email,displayName:'Existing member',googleSubject:null});m.update.mockResolvedValue({count:1});});
function attempt(linkEmail?:string){const begun=beginGoogleSignIn(linkEmail),url=new URL(begun.url),transaction=readGoogleTransaction(begun.cookie,url.searchParams.get('state')!);return {...begun,transaction};}
function exchange(payload?:object){vi.spyOn(OAuth2Client.prototype,'getToken').mockImplementation(async()=>({tokens:{id_token:'test-id-token'},res:null}));return vi.spyOn(OAuth2Client.prototype,'verifyIdToken').mockImplementation(async()=>new LoginTicket('',{iss:'https://accounts.google.com',aud:process.env.GOOGLE_CLIENT_ID!,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+3600,...profile,...payload}));}
function request(a:ReturnType<typeof attempt>,query='code=one-time-code'){return new NextRequest('https://watchtower.test/api/auth/google/callback?state='+a.transaction.state+'&'+query,{headers:{cookie:googleCookie+'='+a.cookie}});}
test('authorization uses only sign-in scopes, state, nonce and S256 PKCE without offline access',()=>{const a=attempt(),url=new URL(a.url);expect(url.origin).toBe('https://accounts.google.com');expect(url.searchParams.get('scope')).toBe('openid email profile');expect(url.searchParams.get('access_type')).toBe('online');expect(url.searchParams.get('code_challenge_method')).toBe('S256');expect(url.searchParams.get('code_challenge')).toBe(createHash('sha256').update(a.transaction.verifier).digest('base64url'));expect(url.searchParams.get('nonce')).toBe(a.transaction.nonce);expect(url.searchParams.get('redirect_uri')).toBe('https://watchtower.test/api/auth/google/callback');expect(attempt().transaction.state).not.toBe(a.transaction.state);});
test('state mismatch, cookie tampering, magic-link substitution and expiry are rejected',()=>{const a=attempt();expect(()=>readGoogleTransaction(a.cookie,'wrong-state')).toThrow('google-expired');expect(()=>readGoogleTransaction(a.cookie+'x',a.transaction.state)).toThrow('google-expired');expect(()=>readGoogleTransaction(tokenFor(profile.email),a.transaction.state)).toThrow('google-expired');vi.useFakeTimers();vi.setSystemTime(Date.now()+600001);expect(()=>readGoogleTransaction(a.cookie,a.transaction.state)).toThrow('google-expired');});
test('public HTTP origins are refused and localhost is supported',()=>{vi.stubEnv('APP_URL','http://unsafe.example');expect(googleOrigin).toThrow('google-unavailable');vi.stubEnv('APP_URL','http://localhost:3000');expect(googleOrigin()).toBe('http://localhost:3000');});
test('token exchange sends the browser verifier and checks the client audience',async()=>{const a=attempt(),verification=exchange({nonce:a.transaction.nonce});expect(await exchangeGoogleCode('code',a.transaction)).toMatchObject(profile);expect(OAuth2Client.prototype.getToken).toHaveBeenCalledWith({code:'code',codeVerifier:a.transaction.verifier});expect(verification).toHaveBeenCalledWith({idToken:'test-id-token',audience:process.env.GOOGLE_CLIENT_ID});});
test.each([{nonce:'wrong'},{email_verified:false},{exp:1},{azp:'another-client'},{email:'invalid'}])('unsafe identity claims fail closed: %j',async(claim)=>{const a=attempt();exchange({nonce:a.transaction.nonce,...claim});await expect(exchangeGoogleCode('code',a.transaction)).rejects.toThrow('google-failed');});
test('cryptographic verification failure does not authenticate',async()=>{const a=attempt();exchange({nonce:a.transaction.nonce}).mockRejectedValue(new Error('Invalid token signature or audience'));const response=await callback(request(a));expect(response.headers.get('location')).toContain('error=google-failed');expect(response.cookies.has('watchtower')).toBe(false);expect(m.upsert).not.toHaveBeenCalled();});
test('existing email-owned accounts are linked without changing their display name or password',async()=>{const user=await accountForGoogle(profile);expect(user.email).toBe(profile.email);expect(m.upsert.mock.calls[0][0].update).toEqual({});expect(m.update).toHaveBeenCalledWith({where:{id:'user-1',googleSubject:null},data:{googleSubject:profile.sub}});});
test('new accounts use the verified subject and profile name',async()=>{m.upsert.mockResolvedValue({id:'new',email:profile.email,googleSubject:profile.sub});await accountForGoogle(profile);expect(m.upsert.mock.calls[0][0].create).toEqual({email:profile.email,googleSubject:profile.sub,displayName:profile.name});expect(m.update).not.toHaveBeenCalled();});
test('new Google profile names respect the account editor length limit',async()=>{await accountForGoogle({...profile,name:'X'.repeat(80)});expect(m.upsert.mock.calls[0][0].create.displayName).toHaveLength(50);});
test('returning Google users follow their subject even if their Google email changes',async()=>{m.find.mockResolvedValue({id:'existing',email:'original@watchtower.test',googleSubject:profile.sub});expect((await accountForGoogle(profile)).email).toBe('original@watchtower.test');expect(m.upsert).not.toHaveBeenCalled();});
test('non-hosted Google email cannot claim an existing email-owned watchlist',async()=>{await expect(accountForGoogle({...profile,email:'person@external.example'})).rejects.toThrow('google-link-required');expect(m.upsert).not.toHaveBeenCalled();});
test('Workspace email may link when Google provides its verified hosted-domain claim',async()=>{await accountForGoogle({...profile,email:'person@workspace.example',hd:'workspace.example'});expect(m.upsert.mock.calls[0][0].where.email).toBe('person@workspace.example');});
test('verified Watchtower users can explicitly connect a non-hosted Google account',async()=>{await accountForGoogle({...profile,email:'person@external.example'},'owner@watchtower.test');expect(m.upsert.mock.calls[0][0].where.email).toBe('owner@watchtower.test');});
test('an identity connected elsewhere cannot be moved onto a different account',async()=>{m.find.mockResolvedValue({id:'other',email:'other@watchtower.test',googleSubject:profile.sub});await expect(accountForGoogle(profile,'owner@watchtower.test')).rejects.toThrow('google-connected-elsewhere');expect(m.upsert).not.toHaveBeenCalled();});
test('a different linked identity cannot be replaced and concurrent linking fails closed',async()=>{m.upsert.mockResolvedValueOnce({id:'user-1',email:profile.email,googleSubject:'different-subject'});await expect(accountForGoogle(profile)).rejects.toThrow('google-connected-elsewhere');m.update.mockResolvedValue({count:0});await expect(accountForGoogle(profile)).rejects.toThrow('google-connected-elsewhere');});
test('start sets an HttpOnly browser transaction cookie',async()=>{const response=await start(new NextRequest('https://watchtower.test/api/auth/google'));expect(response.headers.get('location')).toContain('https://accounts.google.com/');expect(response.cookies.get(googleCookie)).toMatchObject({httpOnly:true,sameSite:'lax',maxAge:600,path:'/api/auth/google'});expect(response.headers.get('cache-control')).toBe('no-store');});
test('unknown hosts are redirected to the configured origin before starting OAuth',async()=>{const response=await start(new NextRequest('https://preview.example/api/auth/google'));expect(response.headers.get('location')).toBe('https://watchtower.test/api/auth/google');expect(response.cookies.has(googleCookie)).toBe(false);});
test('a successful callback sets the existing Watchtower session and consumes the login cookie',async()=>{const a=attempt();exchange({nonce:a.transaction.nonce});const response=await callback(request(a));expect(response.headers.get('location')).toBe('https://watchtower.test/dashboard');expect(verifyToken(response.cookies.get('watchtower')!.value)).toBe(profile.email);expect(response.cookies.get('watchtower')).toMatchObject({httpOnly:true,sameSite:'lax',path:'/'});expect(response.cookies.get(googleCookie)?.maxAge).toBe(0);});
test('a cancelled sign-in clears its transaction without issuing a session',async()=>{const a=attempt();const response=await callback(request(a,'error=access_denied'));expect(response.headers.get('location')).toContain('error=google-cancelled');expect(response.cookies.has('watchtower')).toBe(false);expect(response.cookies.get(googleCookie)?.maxAge).toBe(0);});
test('callback rejects missing state/cookie without contacting Google',async()=>{const getToken=vi.spyOn(OAuth2Client.prototype,'getToken');const response=await callback(new NextRequest('https://watchtower.test/api/auth/google/callback?code=code'));expect(response.headers.get('location')).toContain('error=google-expired');expect(getToken).not.toHaveBeenCalled();});
test('linking is bound to the same authenticated Watchtower account at callback',async()=>{const a=attempt('owner@watchtower.test');m.session=tokenFor('different@watchtower.test');const getToken=vi.spyOn(OAuth2Client.prototype,'getToken');const response=await callback(request(a));expect(response.headers.get('location')).toContain('error=google-expired');expect(getToken).not.toHaveBeenCalled();});
