import {beforeEach,test,expect,vi} from 'vitest';import https from 'node:https';import {PassThrough} from 'node:stream';import {EventEmitter} from 'node:events';import {readFileSync} from 'node:fs';import {gzipSync,brotliCompressSync,deflateSync} from 'node:zlib';
const m=vi.hoisted(()=>({lookup:vi.fn(),ask:vi.fn()}));vi.mock('node:dns/promises',()=>({lookup:m.lookup}));vi.mock('../../src/lib/ai',()=>({ask:m.ask}));
import {extract,resource,scrape} from '../../src/lib/scrape';
const fixture=readFileSync(new URL('../fixtures/amazon-b07gxs35pg.html',import.meta.url),'utf8');
type Reply={body?:string|Buffer;status?:number;type?:string;encoding?:string;location?:string};
function replies(...responses:Reply[]){return vi.spyOn(https,'get').mockImplementation(((_url:unknown,_options:unknown,callback:(r:unknown)=>void)=>{const next=responses.shift();if(!next)throw new Error('Unexpected scraper request');const req=new EventEmitter() as EventEmitter&{destroy:(e?:Error)=>void};req.destroy=e=>{req.emit('error',e);req.emit('close');};queueMicrotask(()=>{const res=Object.assign(new PassThrough(),{statusCode:next.status??200,headers:{'content-type':next.type??'text/html','content-encoding':next.encoding,location:next.location}});res.on('end',()=>req.emit('close'));res.on('close',()=>req.emit('close'));callback(res);res.end(next.body??'');});return req;}) as typeof https.get);}
beforeEach(()=>{m.lookup.mockResolvedValue([{address:'93.184.216.34',family:4}]);m.ask.mockResolvedValue({productName:'Camera',price:42,imageUrl:null});});
test('actual Amazon price fixture matches its displayed sale price',()=>{expect(extract(fixture,'https://www.amazon.fr/dp/B07GXS35PG')).toMatchObject({name:'BISSELL SpotClean ProHeat 330W 36988 Sofa Shampoo',price:149.99,currency:'EUR',stock:'in_stock'});});
test.each(['gzip','br','deflate'] as const)('real markup survives %s transport and more than 2 MB of decoded HTML',async encoding=>{const html='<!--'+' '.repeat(2100000)+'-->'+fixture;const encode={gzip:gzipSync,br:brotliCompressSync,deflate:deflateSync}[encoding];replies({body:encode(html),encoding},{body:'test image',type:'image/jpeg'});const p=await scrape('https://www.amazon.fr/dp/B07GXS35PG');expect(p.price).toBe(149.99);expect(p.imageUrl).toContain('media-amazon.com');expect(m.ask).not.toHaveBeenCalled();});
test('missing price engages AI fallback on available visible text',async()=>{replies({body:'<h1>Camera</h1><meta property="product:price:currency" content="EUR"><p>Today only 42 euros</p>'});expect(await scrape('https://shop.example')).toMatchObject({price:42,currency:'EUR'});expect(m.ask.mock.calls[0][1]).toContain('Today only 42 euros');});
test('JavaScript-only price cannot be invented when fallback returns null',async()=>{m.ask.mockResolvedValue({productName:'Camera',price:null,imageUrl:null});replies({body:'<h1>Camera</h1><div id="price-root"></div><script>renderPrice()</script>'});await expect(scrape('https://shop.example')).rejects.toThrow('reliable price');expect(m.ask).toHaveBeenCalledOnce();expect(m.ask.mock.calls[0][1]).not.toContain('renderPrice');});
test('malformed HTML and JSON-LD use fallback instead of crashing',async()=>{replies({body:'<script type="application/ld+json">{broken</script><h1>Camera<p>42 euros<meta property="product:price:currency" content="EUR">'});expect((await scrape('https://shop.example')).price).toBe(42);expect(m.ask).toHaveBeenCalled();});
test('unknown currency still fails closed after fallback',async()=>{replies({body:'<h1>Camera</h1><p>42</p>'});await expect(scrape('https://shop.example')).rejects.toThrow('currency');});
test('404 metadata image falls back to an actual product gallery image',async()=>{replies({body:'<h1>Camera</h1><meta property="product:price:amount" content="42"><meta property="product:price:currency" content="EUR"><meta property="og:image" content="/gone.jpg"><img alt="Camera" src="/gallery.jpg">'},{status:404},{type:'image/jpeg',body:'image'});expect((await scrape('https://shop.example/product')).imageUrl).toBe('https://shop.example/gallery.jpg');});
test('retailer rate limiting fails before AI',async()=>{replies({status:429});await expect(scrape('https://shop.example')).rejects.toThrow('HTTP 429');expect(m.ask).not.toHaveBeenCalled();});
test('redirects revalidate DNS and reject private destinations',async()=>{m.lookup.mockResolvedValueOnce([{address:'93.184.216.34',family:4}]).mockResolvedValueOnce([{address:'127.0.0.1',family:4}]);const get=replies({status:302,location:'https://internal.example'});await expect(resource('https://shop.example')).rejects.toThrow('Private network');expect(get).toHaveBeenCalledOnce();});
test('decoded response size remains bounded',async()=>{replies({body:gzipSync(Buffer.alloc(16000001,32)),encoding:'gzip'});await expect(resource('https://shop.example')).rejects.toThrow('16 MB');});
test('CAPTCHA is reported explicitly without AI guessing',async()=>{replies({body:'<form action="/errors/validateCaptcha"><input id="captchacharacters"></form>'});await expect(scrape('https://shop.example')).rejects.toThrow('browser verification');expect(m.ask).not.toHaveBeenCalled();});
